65 guardar ambos formatos
datosgobar/infra.datos.gob.ar pull request #69
Opened 2019-08-20 19:51 UTC by FScaccheri

Creo un FileField nuevo para CatalogUpload, que ahora tiene `json_file` y `xlsx_file`:
- En una subida de catálogo, cuando se sube un archivo de un formato (por file upload o url), se crea automaticamente el archivo en el otro formato y se guarda en el modelo.
- Creo storages nuevos para los campos nuevos, deprecando el anterior CatalogUploadStorage. En consecuencia, modifico algunas migraciones que importaban directamente esta clase.
- Modifico el template para que refleje muestre correctamente los archivos disponibles, cuando los hay.
- Agrego tests.

2019-08-20 20:12 UTC, poligarcia requested changes

2019-08-20 20:12 UTC, poligarcia commented on infra/apps/catalog/helpers/temp_file_from_url.py
> +        name = response.url.rsplit('/')[-2]
En vez de usar ese `rsplit` no conviene intentar usar [`os.path`](https://docs.python.org/3/library/os.path.html) o [`url lib.parse`](https://docs.python.org/3/library/urllib.parse.html)?

2019-08-20 20:12 UTC, poligarcia commented on infra/apps/catalog/helpers/temp_file_from_url.py
>      fd = open(f'/{tempfile.gettempdir()}/{name}', 'wb+')
Same as above pero con [`tempfile`](https://docs.python.org/3/library/tempfile.html) (que ya te devuelve un objeto `file` y lo borra cuando termina).

2019-08-20 20:12 UTC, poligarcia commented on infra/apps/catalog/migrations/0001_initial.py
> +                ('file', models.FileField(blank=True, null=True, storage='infra.apps.catalog.storage.catalog_storage.CutomCatalogStorage', upload_to=catalog_file_path)),
Hay un typo en `CutomCatalogStorage`?

2019-08-20 20:45 UTC, lucaslavandeira commented on infra/apps/catalog/models/catalog_upload.py
> +                self.json_file.storage.save_as_latest(self)
Todo esto se puede refactorizar en un patrón Strategy o similar para encapsular diferentes estrategias de escritura de manera más escalable (o sea, para permitir más formatos que 2)

2019-08-20 20:49 UTC, lucaslavandeira commented on infra/apps/catalog/models/catalog_upload.py
> +        if not self.json_file or not self.xlsx_file:
No me cierra esta condición. En el evento de una actualización de uno de los archivos, el otro se debería regenerar, no?

2019-08-21 15:15 UTC, lucaslavandeira commented on infra/apps/catalog/models/catalog_upload.py
> +                self.json_file.storage.save_as_latest(self)
Todo este cacho de código podría estar adentro del `create_new_file` también, no?

2019-08-21 17:25 UTC, lucaslavandeira approved these changes

2019-08-23 13:23 UTC, merged